// POST /api/pipeline - Execute SLOPSHOP AI Feature Modification Pipeline
// GET /api/pipeline - Query active pipeline status and available features

import { SlopshopPipelineEngine } from '../../src/lib/slopshopPipeline';

export const onRequestGet = async () => {
  return Response.json({
    success: true,
    service: 'SLOPSHOP AI Feature Modification Pipeline',
    status: 'online',
    stages: [
      '1. Target Commit & Worktree Checkout',
      '2. AI Coding Agent Execution',
      '3. Real Git Unified Diff Generation',
      '4. SQL Schema Migration Application',
      '5. Sandboxed Build & Test Evidence Verification',
      '6. Immutable Feature Ref Publishing (refs/features/*)',
      '7. CAS Landing & Revert Support'
    ]
  });
};

export const onRequestPost = async ({ request, env }: { request: Request; env: any }) => {
  try {
    const body = await request.json();
    const {
      appId,
      featureName,
      prompt,
      modifications,
      migrationSql,
      agentName,
      committer,
      action
    } = body;

    const engine = new SlopshopPipelineEngine(appId || 'dronehunter');

    if (action === 'land') {
      const featureRef = body.featureRef || `refs/features/${featureName || 'mod'}/5c030af`;
      const landResult = engine.landFeatureRef(featureRef, body.targetRef || 'refs/heads/main');
      return Response.json({ success: true, action: 'land', result: landResult });
    }

    if (action === 'revert') {
      const commitSha = body.commitSha || '5c030af';
      const revertResult = engine.revertFeatureRef(commitSha);
      return Response.json({ success: true, action: 'revert', result: revertResult });
    }

    if (!featureName || !prompt) {
      return Response.json(
        { success: false, error: 'featureName and prompt are required' },
        { status: 400 }
      );
    }

    const defaultMods = Array.isArray(modifications) && modifications.length > 0
      ? modifications
      : [
          {
            path: `src/features/${featureName.toLowerCase().replace(/[^a-z0-9]/g, '_')}.ts`,
            content: `// Feature: ${featureName}\n// Generated by ${agentName || 'AI Agent'}\nexport const ${featureName.replace(/[^a-z0-9]/gi, '')} = {\n  name: "${featureName}",\n  enabled: true,\n  version: "1.0.0"\n};\n`,
            action: 'create' as const
          }
        ];

    const result = await engine.executePipeline({
      appId: appId || 'dronehunter',
      featureName,
      prompt,
      modifications: defaultMods,
      migrationSql,
      agentName,
      committer
    });

    // If D1 is available, record published feature ref in git_refs
    if (env && env.DB && result.featureResult) {
      try {
        await env.DB.prepare(`
          INSERT INTO git_refs (repo_id, ref, sha, committer, updated_at)
          VALUES (?, ?, ?, ?, datetime('now'))
          ON CONFLICT(repo_id, ref) DO UPDATE SET
            sha = excluded.sha,
            committer = excluded.committer,
            updated_at = excluded.updated_at
        `).bind(
          appId || 'dronehunter',
          result.featureResult.featureRef,
          result.featureResult.commitSha,
          committer || 'nate'
        ).run();
      } catch {}
    }

    return Response.json({
      success: true,
      pipeline: 'SLOPSHOP AI Feature Modification Pipeline',
      ...result
    });
  } catch (err: any) {
    return Response.json(
      { success: false, error: 'Pipeline execution failed: ' + (err.message || 'Unknown error') },
      { status: 500 }
    );
  }
};
